import type { Metadata } from "next";
import Header from "@/components/Header";
import SideNav from "@/components/SideNav";
import type { User as NextAuthUser } from "next-auth";
import { auth } from "auth";

type AppUser = NextAuthUser & { id: string; username?: string | null };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const session = await auth();
  const user: AppUser | null = (session?.user as AppUser) ?? null;

  return (
    <div className="flex h-screen relative flex-col md:flex-row md:overflow-hidden bg-background text-foreground">
      <div className="w-20 flex-none lg:w-64 md:border-r border-border">
        <SideNav user={user} />
      </div>

      <div className="flex-grow mt-12 md:mt-0 flex-1 w-full md:overflow-y-auto sm:p-6 md:p-12 max-w-7xl mx-auto">
        <Header />
        {children}
      </div>

      {modal}
    </div>
  );
}
