import type { Metadata } from "next";
import Header from "@/components/Header";
import SideNav from "@/components/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal?: React.ReactNode;
}) {
  return (
    <div className="flex relative flex-col md:flex-row bg-background text-foreground">
      <div className="w-20 flex-none lg:w-64 md:border-r border-border">
        <SideNav />
      </div>

      <div className="page-scroller h-screen flex-1 w-full sm:p-6 md:p-12 max-w-7xl mx-auto">
        <Header />
        {children}
      </div>

      {modal ?? null}
    </div>
  );
}